#pragma once

#include <Libs/Input/Click/Click.h>
#include <Libs/Utility/String/String.h>

#include <nlohmann/json.hpp>

namespace tactics {

template<> class Str<click::DeviceType> {
public:
	static std::string to(click::DeviceType value);
	static click::DeviceType from(std::string_view string);
};

} // namespace tactics

FORMAT_STR(click::DeviceType);

namespace click {

void to_json(nlohmann::json&, const Trigger&);
void from_json(const nlohmann::json& json, Trigger& trigger);
void to_json(nlohmann::json&, const Modifier&);
void from_json(const nlohmann::json& json, Modifier& modifier);

NLOHMANN_JSON_SERIALIZE_ENUM(TriggerType,
							 {{TriggerType::Down, "down"},
							  {TriggerType::Press, "press"},
							  {TriggerType::Release, "release"},
							  {TriggerType::Hold, "hold"},
							  {TriggerType::Continuous, "continuous"}});

NLOHMANN_JSON_SERIALIZE_ENUM(ModifierType, {{ModifierType::Negate, "negate"}, {ModifierType::ToAxis, "toAxis"}});

NLOHMANN_JSON_SERIALIZE_ENUM(Axis, {{Axis::XYZ, "xyz"}, {Axis::YZX, "yzx"}, {Axis::ZXY, "zxy"}});

NLOHMANN_JSON_SERIALIZE_ENUM(ActionType,
							 {{ActionType::Scalar, "scalar"},
							  {ActionType::Axis2D, "axis2d"},
							  {ActionType::Axis3D, "axis3d"}});

NLOHMANN_JSON_SERIALIZE_ENUM(Gesture,
							 {{Gesture::Unknown, "unknown"},
							  {Gesture::LeftButton, "leftButton"},
							  {Gesture::RightButton, "rightButton"},
							  {Gesture::MiddleButton, "middleButton"},
							  {Gesture::MouseX, "mouseX"},
							  {Gesture::MouseY, "mouseY"},
							  {Gesture::MouseZ, "mouseZ"},
							  {Gesture::MouseXY, "mouseXY"},
							  {Gesture::ButtonA, "buttonA"},
							  {Gesture::ButtonB, "buttonB"},
							  {Gesture::ButtonX, "buttonX"},
							  {Gesture::ButtonY, "buttonY"},
							  {Gesture::ButtonBack, "buttonBack"},
							  {Gesture::ButtonGuide, "buttonGuide"},
							  {Gesture::ButtonStart, "buttonStart"},
							  {Gesture::ButtonLeftStick, "buttonLeftStick"},
							  {Gesture::ButtonRightStick, "buttonRightStick"},
							  {Gesture::ButtonLeftShoulder, "buttonLeftShoulder"},
							  {Gesture::ButtonRightShoulder, "buttonRightShoulder"},
							  {Gesture::ButtonDPadUp, "buttonDPadUp"},
							  {Gesture::ButtonDPadDown, "buttonDPadDown"},
							  {Gesture::ButtonDPadRight, "buttonDPadRight"},
							  {Gesture::ButtonDPadLeft, "buttonDPadLeft"},
							  {Gesture::ButtonMisc, "buttonMisc"},
							  {Gesture::ButtonPaddle1, "buttonPaddle1"},
							  {Gesture::ButtonPaddle2, "buttonPaddle2"},
							  {Gesture::ButtonPaddle3, "buttonPaddle3"},
							  {Gesture::ButtonPaddle4, "buttonPaddle4"},
							  {Gesture::ButtonTouchpad, "buttonTouchpad"},
							  {Gesture::AxisLeftX, "axisLeftX"},
							  {Gesture::AxisLeftY, "axisLeftY"},
							  {Gesture::AxisLeftXY, "axisLeftXY"},
							  {Gesture::AxisRightX, "axisRightX"},
							  {Gesture::AxisRightY, "axisRightY"},
							  {Gesture::AxisRightXY, "axisRightXY"},
							  {Gesture::AxisTriggerLeft, "axisTriggerLeft"},
							  {Gesture::AxisTriggerRight, "axisTriggerRight"},
							  {Gesture::Touch1, "touch1"},
							  {Gesture::Touch2, "touch2"},
							  {Gesture::Touch3, "touch3"},
							  {Gesture::Touch4, "touch4"},
							  {Gesture::Touch5, "touch5"},
							  {Gesture::Touch6, "touch6"},
							  {Gesture::Touch7, "touch7"},
							  {Gesture::Touch8, "touch8"},
							  {Gesture::Touch9, "touch9"},
							  {Gesture::Touch10, "touch10"},
							  {Gesture::KeyReturn, "keyReturn"},
							  {Gesture::KeyEscape, "keyEscape"},
							  {Gesture::KeyBackspace, "keyBackspace"},
							  {Gesture::KeyTab, "keyTab"},
							  {Gesture::KeySpace, "keySpace"},
							  {Gesture::KeyExclaim, "keyExclaim"},
							  {Gesture::KeyQuotedbl, "keyQuotedbl"},
							  {Gesture::KeyHash, "keyHash"},
							  {Gesture::KeyPercent, "keyPercent"},
							  {Gesture::KeyDollar, "keyDollar"},
							  {Gesture::KeyAmpersand, "keyAmpersand"},
							  {Gesture::KeyQuote, "keyQuote"},
							  {Gesture::KeyLeftparen, "keyLeftparen"},
							  {Gesture::KeyRightparen, "keyRightparen"},
							  {Gesture::KeyAsterisk, "keyAsterisk"},
							  {Gesture::KeyPlus, "keyPlus"},
							  {Gesture::KeyComma, "keyComma"},
							  {Gesture::KeyMinus, "keyMinus"},
							  {Gesture::KeyPeriod, "keyPeriod"},
							  {Gesture::KeySlash, "keySlash"},
							  {Gesture::Key0, "key0"},
							  {Gesture::Key1, "key1"},
							  {Gesture::Key2, "key2"},
							  {Gesture::Key3, "key3"},
							  {Gesture::Key4, "key4"},
							  {Gesture::Key5, "key5"},
							  {Gesture::Key6, "key6"},
							  {Gesture::Key7, "key7"},
							  {Gesture::Key8, "key8"},
							  {Gesture::Key9, "key9"},
							  {Gesture::KeyColon, "keyColon"},
							  {Gesture::KeySemicolon, "keySemicolon"},
							  {Gesture::KeyLess, "keyLess"},
							  {Gesture::KeyEquals, "keyEquals"},
							  {Gesture::KeyGreater, "keyGreater"},
							  {Gesture::KeyQuestion, "keyQuestion"},
							  {Gesture::KeyAt, "keyAt"},
							  {Gesture::KeyLeftbracket, "keyLeftbracket"},
							  {Gesture::KeyBackslash, "keyBackslash"},
							  {Gesture::KeyRightbracket, "keyRightbracket"},
							  {Gesture::KeyCaret, "keyCaret"},
							  {Gesture::KeyUnderscore, "keyUnderscore"},
							  {Gesture::KeyBackquote, "keyBackquote"},
							  {Gesture::KeyA, "keyA"},
							  {Gesture::KeyB, "keyB"},
							  {Gesture::KeyC, "keyC"},
							  {Gesture::KeyD, "keyD"},
							  {Gesture::KeyE, "keyE"},
							  {Gesture::KeyF, "keyF"},
							  {Gesture::KeyG, "keyG"},
							  {Gesture::KeyH, "keyH"},
							  {Gesture::KeyI, "keyI"},
							  {Gesture::KeyJ, "keyJ"},
							  {Gesture::KeyK, "keyK"},
							  {Gesture::KeyL, "keyL"},
							  {Gesture::KeyM, "keyM"},
							  {Gesture::KeyN, "keyN"},
							  {Gesture::KeyO, "keyO"},
							  {Gesture::KeyP, "keyP"},
							  {Gesture::KeyQ, "keyQ"},
							  {Gesture::KeyR, "keyR"},
							  {Gesture::KeyS, "keyS"},
							  {Gesture::KeyT, "keyT"},
							  {Gesture::KeyU, "keyU"},
							  {Gesture::KeyV, "keyV"},
							  {Gesture::KeyW, "keyW"},
							  {Gesture::KeyX, "keyX"},
							  {Gesture::KeyY, "keyY"},
							  {Gesture::KeyZ, "keyZ"},
							  {Gesture::KeyCapslock, "keyCapslock"},
							  {Gesture::KeyF1, "keyF1"},
							  {Gesture::KeyF2, "keyF2"},
							  {Gesture::KeyF3, "keyF3"},
							  {Gesture::KeyF4, "keyF4"},
							  {Gesture::KeyF5, "keyF5"},
							  {Gesture::KeyF6, "keyF6"},
							  {Gesture::KeyF7, "keyF7"},
							  {Gesture::KeyF8, "keyF8"},
							  {Gesture::KeyF9, "keyF9"},
							  {Gesture::KeyF10, "keyF10"},
							  {Gesture::KeyF11, "keyF11"},
							  {Gesture::KeyF12, "keyF12"},
							  {Gesture::KeyPrintscreen, "keyPrintscreen"},
							  {Gesture::KeyScrolllock, "keyScrolllock"},
							  {Gesture::KeyPause, "keyPause"},
							  {Gesture::KeyInsert, "keyInsert"},
							  {Gesture::KeyHome, "keyHome"},
							  {Gesture::KeyPageup, "keyPageup"},
							  {Gesture::KeyDelete, "keyDelete"},
							  {Gesture::KeyEnd, "keyEnd"},
							  {Gesture::KeyPagedown, "keyPagedown"},
							  {Gesture::KeyRight, "keyRight"},
							  {Gesture::KeyLeft, "keyLeft"},
							  {Gesture::KeyDown, "keyDown"},
							  {Gesture::KeyUp, "keyUp"},
							  {Gesture::KeyNumlockclear, "keyNumlockclear"},
							  {Gesture::KeypadDivide, "keypadDivide"},
							  {Gesture::KeypadMultiply, "keypadMultiply"},
							  {Gesture::KeypadMinus, "keypadMinus"},
							  {Gesture::KeypadPlus, "keypadPlus"},
							  {Gesture::KeypadEnter, "keypadEnter"},
							  {Gesture::Keypad1, "keypad1"},
							  {Gesture::Keypad2, "keypad2"},
							  {Gesture::Keypad3, "keypad3"},
							  {Gesture::Keypad4, "keypad4"},
							  {Gesture::Keypad5, "keypad5"},
							  {Gesture::Keypad6, "keypad6"},
							  {Gesture::Keypad7, "keypad7"},
							  {Gesture::Keypad8, "keypad8"},
							  {Gesture::Keypad9, "keypad9"},
							  {Gesture::Keypad0, "keypad0"},
							  {Gesture::KeypadPeriod, "keypadPeriod"},
							  {Gesture::KeyApplication, "keyApplication"},
							  {Gesture::KeyPower, "keyPower"},
							  {Gesture::KeypadEquals, "keypadEquals"},
							  {Gesture::KeyF13, "keyF13"},
							  {Gesture::KeyF14, "keyF14"},
							  {Gesture::KeyF15, "keyF15"},
							  {Gesture::KeyF16, "keyF16"},
							  {Gesture::KeyF17, "keyF17"},
							  {Gesture::KeyF18, "keyF18"},
							  {Gesture::KeyF19, "keyF19"},
							  {Gesture::KeyF20, "keyF20"},
							  {Gesture::KeyF21, "keyF21"},
							  {Gesture::KeyF22, "keyF22"},
							  {Gesture::KeyF23, "keyF23"},
							  {Gesture::KeyF24, "keyF24"},
							  {Gesture::KeyExecute, "keyExecute"},
							  {Gesture::KeyHelp, "keyHelp"},
							  {Gesture::KeyMenu, "keyMenu"},
							  {Gesture::KeySelect, "keySelect"},
							  {Gesture::KeyStop, "keyStop"},
							  {Gesture::KeyAgain, "keyAgain"},
							  {Gesture::KeyUndo, "keyUndo"},
							  {Gesture::KeyCut, "keyCut"},
							  {Gesture::KeyCopy, "keyCopy"},
							  {Gesture::KeyPaste, "keyPaste"},
							  {Gesture::KeyFind, "keyFind"},
							  {Gesture::KeyMute, "keyMute"},
							  {Gesture::KeyVolumeup, "keyVolumeup"},
							  {Gesture::KeyVolumedown, "keyVolumedown"},
							  {Gesture::KeypadComma, "keypadComma"},
							  {Gesture::KeypadEqualsas400, "keypadEqualsas400"},
							  {Gesture::KeyAlterase, "keyAlterase"},
							  {Gesture::KeySysreq, "keySysreq"},
							  {Gesture::KeyCancel, "keyCancel"},
							  {Gesture::KeyClear, "keyClear"},
							  {Gesture::KeyPrior, "keyPrior"},
							  {Gesture::KeyReturn2, "keyReturn2"},
							  {Gesture::KeySeparator, "keySeparator"},
							  {Gesture::KeyOut, "keyOut"},
							  {Gesture::KeyOper, "keyOper"},
							  {Gesture::KeyClearagain, "keyClearagain"},
							  {Gesture::KeyCrsel, "keyCrsel"},
							  {Gesture::KeyExsel, "keyExsel"},
							  {Gesture::Keypad00, "keypad00"},
							  {Gesture::Keypad000, "keypad000"},
							  {Gesture::KeyThousandsseparator, "keyThousandsseparator"},
							  {Gesture::KeyDecimalseparator, "keyDecimalseparator"},
							  {Gesture::KeyCurrencyunit, "keyCurrencyunit"},
							  {Gesture::KeyCurrencysubunit, "keyCurrencysubunit"},
							  {Gesture::KeypadLeftparen, "keypadLeftparen"},
							  {Gesture::KeypadRightparen, "keypadRightparen"},
							  {Gesture::KeypadLeftbrace, "keypadLeftbrace"},
							  {Gesture::KeypadRightbrace, "keypadRightbrace"},
							  {Gesture::KeypadTab, "keypadTab"},
							  {Gesture::KeypadBackspace, "keypadBackspace"},
							  {Gesture::KeypadA, "keypadA"},
							  {Gesture::KeypadB, "keypadB"},
							  {Gesture::KeypadC, "keypadC"},
							  {Gesture::KeypadD, "keypadD"},
							  {Gesture::KeypadE, "keypadE"},
							  {Gesture::KeypadF, "keypadF"},
							  {Gesture::KeypadXor, "keypadXor"},
							  {Gesture::KeypadPower, "keypadPower"},
							  {Gesture::KeypadPercent, "keypadPercent"},
							  {Gesture::KeypadLess, "keypadLess"},
							  {Gesture::KeypadGreater, "keypadGreater"},
							  {Gesture::KeypadAmpersand, "keypadAmpersand"},
							  {Gesture::KeypadDblampersand, "keypadDblampersand"},
							  {Gesture::KeypadVerticalbar, "keypadVerticalbar"},
							  {Gesture::KeypadDblverticalbar, "keypadDblverticalbar"},
							  {Gesture::KeypadColon, "keypadColon"},
							  {Gesture::KeypadHash, "keypadHash"},
							  {Gesture::KeypadSpace, "keypadSpace"},
							  {Gesture::KeypadAt, "keypadAt"},
							  {Gesture::KeypadExclam, "keypadExclam"},
							  {Gesture::KeypadMemstore, "keypadMemstore"},
							  {Gesture::KeypadMemrecall, "keypadMemrecall"},
							  {Gesture::KeypadMemclear, "keypadMemclear"},
							  {Gesture::KeypadMemadd, "keypadMemadd"},
							  {Gesture::KeypadMemsubtract, "keypadMemsubtract"},
							  {Gesture::KeypadMemmultiply, "keypadMemmultiply"},
							  {Gesture::KeypadMemdivide, "keypadMemdivide"},
							  {Gesture::KeypadPlusminus, "keypadPlusminus"},
							  {Gesture::KeypadClear, "keypadClear"},
							  {Gesture::KeypadClearentry, "keypadClearentry"},
							  {Gesture::KeypadBinary, "keypadBinary"},
							  {Gesture::KeypadOctal, "keypadOctal"},
							  {Gesture::KeypadDecimal, "keypadDecimal"},
							  {Gesture::KeypadHexadecimal, "keypadHexadecimal"},
							  {Gesture::KeyLctrl, "keyLctrl"},
							  {Gesture::KeyLshift, "keyLshift"},
							  {Gesture::KeyLalt, "keyLalt"},
							  {Gesture::KeyLgui, "keyLgui"},
							  {Gesture::KeyRctrl, "keyRctrl"},
							  {Gesture::KeyRshift, "keyRshift"},
							  {Gesture::KeyRalt, "keyRalt"},
							  {Gesture::KeyRgui, "keyRgui"},
							  {Gesture::KeyMode, "keyMode"},
							  {Gesture::KeyAudionext, "keyAudionext"},
							  {Gesture::KeyAudioprev, "keyAudioprev"},
							  {Gesture::KeyAudiostop, "keyAudiostop"},
							  {Gesture::KeyAudioplay, "keyAudioplay"},
							  {Gesture::KeyAudiomute, "keyAudiomute"},
							  {Gesture::KeyMediaselect, "keyMediaselect"},
							  {Gesture::KeyWww, "keyWww"},
							  {Gesture::KeyMail, "keyMail"},
							  {Gesture::KeyCalculator, "keyCalculator"},
							  {Gesture::KeyComputer, "keyComputer"},
							  {Gesture::KeyAcSearch, "keyAcSearch"},
							  {Gesture::KeyAcHome, "keyAcHome"},
							  {Gesture::KeyAcBack, "keyAcBack"},
							  {Gesture::KeyAcForward, "keyAcForward"},
							  {Gesture::KeyAcStop, "keyAcStop"},
							  {Gesture::KeyAcRefresh, "keyAcRefresh"},
							  {Gesture::KeyAcBookmarks, "keyAcBookmarks"},
							  {Gesture::KeyBrightnessdown, "keyBrightnessdown"},
							  {Gesture::KeyBrightnessup, "keyBrightnessup"},
							  {Gesture::KeyDisplayswitch, "keyDisplayswitch"},
							  {Gesture::KeyKbdillumtoggle, "keyKbdillumtoggle"},
							  {Gesture::KeyKbdillumdown, "keyKbdillumdown"},
							  {Gesture::KeyKbdillumup, "keyKbdillumup"},
							  {Gesture::KeyEject, "keyEject"},
							  {Gesture::KeySleep, "keySleep"},
							  {Gesture::KeyApp1, "keyApp1"},
							  {Gesture::KeyApp2, "keyApp2"},
							  {Gesture::KeyAudiorewind, "keyAudiorewind"},
							  {Gesture::KeyAudiofastforward, "keyAudiofastforward"},
							  {Gesture::KeySoftleft, "keySoftleft"},
							  {Gesture::KeySoftright, "keySoftright"},
							  {Gesture::KeyCall, "keyCall"},
							  {Gesture::KeyEndcall, "keyEndcall"}});

} // namespace click
