name: Windows Unit Tests

on:
  workflow_run:
    workflows: ["Windows Build"]
    types:
      - completed

jobs:
  unit-tests:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        architecture: [x64, x86]

    steps:
    - name: Download [${{ matrix.configuration }} ${{ matrix.architecture }}] build artifacts
      uses: actions/download-artifact@v4
      with:
        name: unit-test-build-windows-${{ matrix.configuration }}-${{ matrix.architecture }}
        path:  ${{github.workspace}}/build/${{ matrix.configuration }}/src/Apps/ProjectTactics_UnitTests/

    - name: Run unit tests
      run: ctest --output-on-failure --test-dir ${{ matrix.configuration }}/build/${{ matrix.configuration }}/src/Apps/ProjectTactics_UnitTests/
