name: Windows Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        configuration: [Debug, Release]
        architecture: [x64, Win32]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Configure [${{ matrix.configuration }}] build
      run: cmake -G "Visual Studio 17 2022" -A ${{ matrix.architecture }} -DCMAKE_BUILD_TYPE=${{ matrix.configuration }} -S ./ -B ./build/${{ matrix.configuration }}

    - name: Build [${{ matrix.configuration }}] target
      run: cmake --build ./build/${{ matrix.configuration }} --config ${{ matrix.configuration }}

    - name: Upload Unit Test build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: unit-test-build-windows-${{ matrix.configuration }}-${{ matrix.architecture }}
        path: ${{github.workspace}}/build/${{ matrix.configuration }}/src/Apps/ProjectTactics_UnitTests/
        if-no-files-found: error
        retention-days: 1

  unit-tests:
    runs-on: windows-latest
    needs: build

    strategy:
      matrix:
        configuration: [Debug, Release]
        architecture: [x64, Win32]

    steps:
    - name: Download [${{ matrix.configuration }} ${{ matrix.architecture }}] build artifacts
      uses: actions/download-artifact@v4
      with:
        name: unit-test-build-windows-${{ matrix.configuration }}-${{ matrix.architecture }}
        path:  ${{github.workspace}}/build/${{ matrix.configuration }}/src/Apps/ProjectTactics_UnitTests/

    - name: Run unit tests
      run: ctest --output-on-failure --test-dir ${{github.workspace}}/build/${{ matrix.configuration }}/src/Apps/ProjectTactics_UnitTests/
