name: Windows - Debug Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-windows:
    uses: ./.github/reusable-workflows/windows-build.yml
    with:
      configuration: release
